export { default as StudentsMain } from './StudentsMain'
export { default as StudentAdd } from './StudentAdd'
export { default as StudentView } from './StudentView'
export { default as StudentCard } from './StudentCard'
export { default as StudentEdit } from './StudentEdit'
